// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc250.FRCPowerUpTest.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc250.FRCPowerUpTest.Robot;

/**
 *
 */
public class ArmJoystickControl extends Command {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public ArmJoystickControl() {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.arm);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	@Override
	protected void initialize() {

	}

	// Called repeatedly when this Command is scheduled to run
	@Override
	protected void execute() {
		if (Robot.oi.getRightJoy() <= Robot.prefs2.getDouble("Arm Controller Deadband")) {
			Robot.arm.setArmTargetPosition(
					Robot.arm.getCurrentRawPosition() + Robot.prefs2.getInt("Arm Manual Increment"));
		} else if (Robot.oi.getRightJoy() >= -Robot.prefs2.getDouble("Arm Controller Deadband")) {
			Robot.arm.setArmTargetPosition(
					Robot.arm.getCurrentRawPosition() - Robot.prefs2.getInt("Arm Manual Increment"));
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	@Override
	protected boolean isFinished() {
		if (Math.abs(Robot.oi.getRightJoy()) <= Robot.prefs2.getDouble("Arm Controller Deadband")) {
			Robot.arm.setArmTargetPosition(
					Robot.arm.getCurrentRawPosition());
			return true;
		} else {
			return false;
		}
	}

	// Called once after isFinished returns true
	@Override
	protected void end() {
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	@Override
	protected void interrupted() {
	}
}
